import type {Metadata} from "next";

import "./globals.css";
import {Layout} from "@/components/layout";

export const metadata: Metadata = {
    title: "Daily food tracker",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon.ico",
        apple: "/icon-192x192.png",
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link rel="icon" href="/favicon.ico" />
                <link rel="apple-touch-icon" href="/icon-192x192.png" />
                <link rel="manifest" href="/manifest.json" />
            </head>
            <body className="ss">
                <Layout>{children}</Layout>
            </body>
        </html>
    );
}
