import type {Metadata} from "next";

import "./globals.css";
import {Layout} from "@/components/layout";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="ss">
                <Layout>{children}</Layout>
            </body>
        </html>
    );
}
